/**
 * MEDIA-COVERAGE.md — the report a reviewer reads to see what the library actually
 * covers, written by `content:build`. Split out of the builder so the builder stays a
 * sequence of steps rather than a thousand lines.
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..', '..');

export function writeCoverage({ regions, exercises, animations, presentations }) {
  const lines = [
    '# Media and region coverage',
    '',
    'Generated by `scripts/build-content.mjs`. `npm run content:validate` fails the build',
    'when a published exercise has no approved media, or when a region resolves to zero',
    'published exercises without an explicit empty state.',
    '',
    '## Library',
    '',
    '| metric | value |',
    '| --- | --- |',
    `| regions | ${regions.length} |`,
    `| presentations | ${presentations.length} |`,
    `| exercises | ${exercises.length} |`,
    `| timelines | ${animations.length} |`,
    `| timelines signed off | ${animations.filter((a) => a.status === 'published').length} |`,
    `| rig-driven | ${exercises.filter((e) => e.mediaKind === 'rig_animation').length} |`,
    `| still sequence | ${exercises.filter((e) => e.mediaKind === 'still_sequence').length} |`,
    '',
    '## Coverage by family',
    '',
    '| family | regions | with exercises | guidance-only | signed timelines | media kind |',
    '| --- | --- | --- | --- | --- | --- |',
  ];
  const families = [...new Set(regions.map((r) => r.family))].sort();
  for (const family of families) {
    const rs = regions.filter((r) => r.family === family);
    const withEx = rs.filter((r) => (r.exerciseIds ?? []).length);
    const guidance = rs.filter((r) => r.emptyState);
    const ids = new Set(withEx.map((e) => e.id));
    const signed = animations.filter(
      (a) => ids.has(a.exerciseId) && a.status === 'published',
    ).length;
    const kinds = [...new Set(exercises.filter((e) => ids.has(e.id)).map((e) => e.mediaKind))];
    lines.push(
      `| ${family} | ${rs.length} | ${withEx.length} | ${guidance.length} | ${signed} | ${kinds.join(', ') || '—'} |`,
    );
  }
  lines.push('', '## Borrowed ladders', '');
  lines.push(
    'Patterns added in v2 inherit the exercise pool named below, then apply their own',
    'range caps, dose and contraindications. Nothing is invented to fill a gap.',
    '',
    presentations
      .filter((p) => (p.shares ?? []).length)
      .map((p) => `- \`${p.id}\` shares the \`${p.shares.join('`, `')}\` pool`)
      .join('\n') || '- none',
    '',
  );
  lines.push('', '## Positions, equipment, types', '');
  const tally = (key) => {
    const counts = new Map();
    for (const e of exercises) counts.set(e[key], (counts.get(e[key]) ?? 0) + 1);
    return [...counts.entries()].sort((a, b) => b[1] - a[1]);
  };
  for (const key of ['positionRequired', 'equipment', 'type', 'laterality', 'phase']) {
    const items = tally(key).map(([k, v]) => `${k} ${v}`);
    const label = `- **${key}**: `;
    let line = label;
    for (const item of items) {
      const piece = (line === label ? '' : ' \u00b7 ') + item;
      if (line !== label && line.length + piece.length > 108) {
        lines.push(line);
        line = '  ' + item;
        continue;
      }
      line += piece;
    }
    lines.push(line);
  }
  lines.push(
    '',
    '## Unmatched movement names',
    '',
    'Exercises whose name did not match a movement template fall back to the generic',
    'mobility clip and are marked `still_sequence`. They are real prescriptions with a',
    'written cue set and no fabricated demonstration.',
    '',
  );
  fs.writeFileSync(path.join(ROOT, 'MEDIA-COVERAGE.md'), `${lines.join('\n')}\n`);
}
