/**
 * Asset loading for the body. The GLB is generated by `npm run assets:build` and carries
 * the region identity per vertex (`_REGIONID`) plus a thickness channel (`_THIN`), so no
 * texture atlas has to be sampled on the CPU to know what was tapped.
 */

import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import * as THREE from 'three';
import manifest from '@/data/models.json';

export type Sex = 'male' | 'female';

export type BodyAsset = {
  file: string;
  url: string;
  hash: string;
  bytes: number;
  triangles: number;
};

/**
 * The URL comes from the build manifest, not a constant: the filename carries the digest of
 * the mesh, so the browser can cache it forever and a stale body can never be served against a
 * fresh region table.
 */
export const BODY_ASSETS = manifest as unknown as Record<Sex, BodyAsset>;

export const MODEL_URL: Record<Sex, string> = {
  male: BODY_ASSETS.male.url,
  female: BODY_ASSETS.female.url,
};

type Loaded = { geometry: THREE.BufferGeometry; material: THREE.MeshStandardMaterial };

const cache = new Map<Sex, Promise<Loaded>>();

/** GLTFLoader lower-cases attribute names it does not know. */
export function attr(geometry: THREE.BufferGeometry, name: string) {
  const lower = name.toLowerCase();
  return geometry.getAttribute(lower) ?? geometry.getAttribute(name);
}

let webgl: boolean | null = null;

export function hasWebGL(): boolean {
  if (webgl !== null) return webgl;
  if (typeof window === 'undefined') return false;
  try {
    const canvas = document.createElement('canvas');
    const gl =
      canvas.getContext('webgl2', { failIfMajorPerformanceCaveat: true }) ??
      canvas.getContext('webgl', { failIfMajorPerformanceCaveat: true });
    webgl = Boolean(gl);
    gl?.getExtension('WEBGL_lose_context')?.loseContext();
  } catch {
    webgl = false;
  }
  return webgl;
}

function firstMesh(scene: THREE.Object3D): THREE.Mesh | null {
  let found: THREE.Mesh | null = null;
  scene.traverse((object) => {
    if (found) return;
    if ((object as THREE.Mesh).isMesh) found = object as THREE.Mesh;
  });
  return found;
}

/**
 * Loads once per sex, then hands out the same geometry. Both the locator and the
 * demonstrator clone from here, which is what makes them visually identical by
 * construction rather than by convention.
 */
export function loadBody(sex: Sex, onProgress?: (ratio: number) => void): Promise<Loaded> {
  const existing = cache.get(sex);
  if (existing) return existing;
  const loader = new GLTFLoader();
  const promise = loader
    .loadAsync(MODEL_URL[sex], (event) => {
      if (!onProgress) return;
      const total = event.total || BODY_ASSETS[sex].bytes;
      onProgress(Math.min(1, event.loaded / total));
    })
    .then((gltf) => {
      const mesh = firstMesh(gltf.scene);
      if (!mesh) throw new Error(`${MODEL_URL[sex]} contains no mesh`);
      const geometry = mesh.geometry;
      if (!attr(geometry, '_REGIONID')) {
        throw new Error(`${MODEL_URL[sex]} is missing the _REGIONID channel: re-run assets:build`);
      }
      const material = (
        Array.isArray(mesh.material) ? mesh.material[0] : mesh.material
      ) as THREE.MeshStandardMaterial;
      geometry.computeBoundingSphere();
      return { geometry, material: material.clone() };
    })
    .catch((error) => {
      cache.delete(sex);
      throw error;
    });
  cache.set(sex, promise);
  return promise;
}

export function isLoaded(sex: Sex): boolean {
  return cache.has(sex);
}

/** Bytes of the mesh being fetched, for the loading copy the shell shows. */
export const modelBytes = (sex: Sex) => BODY_ASSETS[sex].bytes;
